services:
  - type: web
    name: Pillcare-web
    env: python
    plan: free  # หรือปรับเป็นตามแผนที่คุณต้องการ
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"