services:
  - type: web
    name: Pillcare-web
    env: python
    plan: free  # หรือปรับเป็นตามแผนที่คุณต้องการ
    pythonVersion: 3.10.12
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn API.app:app"
